Add ring buffer when monitoring network syscalls
bob-yamong/youmuu pull request #12
Opened 2024-10-23 08:24 UTC by eeche

### Description

- refactor frequently used code into an inline function
- network activity monitoring logs are now passed into the ring buffer
- seperate code into handler.h and handler.c for improved modularity and organization
- change codebase from C to C++

### Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Refactor (code improvement that does not add functionality)
- [ ] Documentation update (README, changelog, or other documentation)
- [ ] Other (please explain):

### Checklist

- [x] I have read the [CONTRIBUTING.md](./.github/docs/CONTRIBUTING.md) document
- [x] My code follows the code style of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings or errors

### Additional Notes

- multi-threading tasks need to be implemented
- filesystem and process monitoring should be updated and extended

2024-10-23 15:05 UTC, TwoTwo-me requested changes
전반적으로 코드 줄 수가 최적화 된 다음 다시 리뷰 진행하고 싶어요.

2024-10-23 15:05 UTC, TwoTwo-me commented on src/tracepoint/event.h
> +};
debug 용으로 count 찍히면 좋을듯

2024-10-23 15:05 UTC, TwoTwo-me commented on src/tracepoint/tracepoint.bpf.c
> +        return 0;
반복되는 구조.

2024-10-23 15:05 UTC, TwoTwo-me commented on src/tracepoint/tracepoint.c
void init_event_table() 분리해주세요.
static int handle_event(void *ctx, void *data, size_t data_sz) 분리해주세요. 비교 회수 개선해주세요. O(1)이면 될 코드를 O(n)으로 해결중입니다.

2024-10-24 07:57 UTC, harksu reviewed
일단 RC가 올라가있는 상태이므로, 추후에 다시 리뷰할게요!

2024-10-24 07:57 UTC, harksu commented on src/tracepoint/handler.c
> +    unsigned long long nanoseconds = task->timestamp % 1000000000;
이런 상수들은 위에서 define하는게 재활용성이 더 좋아보입니다 :)

2024-10-24 22:10 UTC, TwoTwo-me commented on src/tracepoint/handler.c
> +    boot_time = current_time - si.uptime;
boottime 을 시스템 시작 후  1회만 실행해도 된다면 굳이 get_task_info_str 안에서 할 필요가 있을까요?

2024-10-24 22:10 UTC, TwoTwo-me commented on src/tracepoint/handler.c
> +    }
매 시스템 호출 마다 initialized를 검사할 필요가 있는지는 모르겠습니다.
main함수에서 명시적으로 init_event_handlers()를 호출해 주어도 괜찮지 않을까요?

2024-10-24 22:10 UTC, TwoTwo-me commented on src/tracepoint/tracepoint.bpf.c
LGTM 전반적인 구조만틀 보았을때 훌륭해 보입니다.
다른 누군가 더 자세한 리뷰를 써주시길 바랍니다...

2024-10-24 22:10 UTC, TwoTwo-me commented on src/tracepoint/tracepoint.c
handler 쪽으로 분리한것 잘 보았습니다.
이전 comment에서 switch 문 대신 다른 방법을 찾으라고 하였는데. switch문도 내부적으로 lookup table 생성하여 충분히 빠르다고 합니다. 죄송합니다.

하지만 그럼에도 함수포인터 테이블은 더 효율적일겁니다...?

2024-10-24 22:12 UTC, TwoTwo-me commented on src/tracepoint/tracepoint.c
> void init_event_table() 분리해주세요. static int handle_event(void *ctx, void *data, size_t data_sz) 분리해주세요. 비교 회수 개선해주세요. O(1)이면 될 코드를 O(n)으로 해결중입니다.

잘못된 comment 비교회수는 switch문도 충분히 효율적

2024-10-26 04:21 UTC, TwoTwo-me approved these changes

2024-10-26 04:21 UTC, merged