Added ability to add yaml policy
bob-yamong/youmuu pull request #13
Opened 2024-10-23 09:54 UTC by tomorrow9913

### Description

Modified to allow policy updates via yaml

**sample yaml**
```yaml
apiVersion: policy.yamong.com/v1
name: multi-container-example-policy

policys:
  containers:
    - container_name: sharp_yalow
      policies:
        file:
          - path: "/etc/passwd"
            flags:
              - POLICY_ALLOW
              - POLICY_AUDIT
              - POLICY_FILE_READ
            uid: 
              - 1000
              - 1001
          - path: "/var/log"
            flags:
              - POLICY_ALLOW
              - POLICY_AUDIT
              - POLICY_FILE_WRITE
              - POLICY_FILE_APPEND
              - POLICY_RECURSIVE
            uid: 
              - 1000
              - 1001   
          - path: "/sys"
            flags:
              - POLICY_ALLOW
              - POLICY_AUDIT
              - POLICY_FILE_WRITE
              - POLICY_FILE_APPEND
              - POLICY_RECURSIVE
            uid: 
              - 1000
              - 1001   
        network:
          - ip: "192.168.1.100"
            port: 80
            protocol: 6  # TCP
            flags:
              - POLICY_ALLOW
              - POLICY_AUDIT
              - POLICY_NET_CONNECT
            uid: 
              - 1000
              - 1001   
          - ip: "10.0.0.0/8"
            port: 443
            protocol: 6  # TCP
            flags:
              - POLICY_NET_CONNECT
              - POLICY_DENY
            uid: 
              - 1000
              - 1001   
        process:
          - comm: "nginx"
            flags:
              - POLICY_ALLOW
              - POLICY_AUDIT
              - POLICY_PROC_EXEC
            uid: 
              - 1000
              - 1001   
          - comm: "bash"
            flags:
              - POLICY_ALLOW
              - POLICY_AUDIT
              - POLICY_PROC_EXEC
            uid: 
              - 1000
              - 1001
```

### Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (code improvement that does not add functionality)
- [ ] Documentation update (README, changelog, or other documentation)
- [ ] Other (please explain):

### Checklist

- [ ] I have read the [CONTRIBUTING.md](./.github/docs/CONTRIBUTING.md) document
- [ ] My code follows the code style of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings or errors

2024-10-23 09:56 UTC, tomorrow9913 commented
@harksu
@persona-twotwo

2024-10-23 14:35 UTC, tomorrow9913 commented on src/lsm/enforcement
이거 왜 들어와있지?
하지만 바이너리는 최종에 적용되지 않았을 겁니다.

2024-10-24 08:14 UTC, harksu requested changes
주석이 많아서 설명을 보기엔 좋지만, 문자열 비교 관련해서는 함수를 통해서 안전하게 비교하는게 더 좋을 것 같아요 👍

2024-10-24 08:14 UTC, harksu commented on src/lsm/enforcement.cpp
> +        if (!container.file_policies.empty()) {
부정연산자가 짧게해줘서 좋긴하지만, 지금 처럼 특정 객체의 속성으로 깊게 들어가는 경우 오히려 부정연산자가 헷갈리게 하는 경우가 있는 것 같습니다.
베스트는 false에 대한 컨디션 분기보단 true에 대한 컨디션 분기를 하는거라고 생각하는데, 이 로직에서는 해당이 없으니
개인적인 스타일이긴하지만, !(container.file_policies.emplty()) 처럼 한 번 괄호로 묶는 건 어떨까요?

2024-10-24 08:14 UTC, harksu commented on src/lsm/enforcement.cpp
> +        if (!container.file_policies.empty()) {
```suggestion
        if (!(container.file_policies.empty())) {
```

2024-10-24 08:14 UTC, harksu commented on src/lsm/parser.h
> +        return policy;
파일 열기를 실패했는데 정책을 왜 반환한다는건 무슨 의미인가요? 빈객체라 데이터가 없을텐데

2024-10-24 08:14 UTC, harksu commented on src/lsm/parser.h
> +                if (!context.empty() && context.back() == "policies") {
```suggestion
                if (!(context.empty()) && (context.back() == "policies")) {
```

2024-10-24 08:14 UTC, harksu commented on src/lsm/parser.h
> +                if (current_field == "flags") {
compaer함수나 strcmp함수처럼 함수사용해서 문자열 비교하는게 더 좋은 로직 같습니다 :)

2024-10-24 08:20 UTC, tomorrow9913 commented on src/lsm/parser.h
> +        return policy;
일단 리턴형식이 Policy라 다른 형식의 값 리턴하는게 안됩니다.
빈객체를 리턴하면 확인해보고 기존 정책 사용쪽으로 하는건 어떨까요

2024-10-24 08:22 UTC, tomorrow9913 commented on src/lsm/parser.h
> +                if (current_field == "flags") {
`current_field`는 `std::string` 객체입니다 문자열 비교를 위해서는 
`!strcmp(current_field.c_str(), "flages")` 와 같이 비교를 해야해서 위와 같이 비교하였습니다

2024-10-24 12:33 UTC, merged